# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    deps: [check]
  check:
    - task: test
    - task: lint
    - task: fmt
    - git diff --exit-code
  fix: cargo clippy --fix {{.CLIPPY}} {{.CLI_ARGS}}
  fmt: cargo fmt {{.FMT}} {{.CLI_ARGS}}
  lint: cargo clippy {{.CLIPPY}} {{.CLI_ARGS}}
  test:
    cmds:
      - cargo test {{.TEST}} {{.CLI_ARGS}}
    env:
      RUST_BACKTRACE: 1

vars:
  CLIPPY: '--all-targets --all-features -- -Dwarnings'
  FMT: '--all'
  TEST: ''
