[package]
name = "switchbot-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "A library to to interact with the SwitchBot API and control your SwitchBot devices programmatically."
keywords = ["switchbot"]
repository.workspace = true
readme = "README.md"
license.workspace = true

[dependencies]
reqwest = { version = "0.12.18", features = ["json"] }
tokio = { version = "1", features = ["full"] }
hmac = "0.12"
sha2 = "0.10"
uuid = { version = "1", features = ["v4"] }
base64 = "0.22.1"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
log = "0.4.27"
anyhow = { version = "1.0.98", features = ["backtrace"] }
thiserror = "2.0.12"
